### ISSUE TITLE
Error: Failed to load config "./.config/eslint.config" to extend from.

### ISSUE THREAD

**Issue by yodakaEngineer** [floating-ui/floating-ui#1485]
### Issue description
When I installed @popperjs/core and build project, I found this warning.

```
WARNING in ./node_modules/@popperjs/core/lib/index.js
Module Warning (from ./node_modules/eslint-loader/dist/cjs.js):
Failed to load config "./.config/eslint.config" to extend from.
Referenced from: /var/www/app/node_modules/@popperjs/core/package.json
Error: Failed to load config "./.config/eslint.config" to extend from.
Referenced from: /var/www/app/node_modules/@popperjs/core/package.json
    at configInvalidError (/var/www/app/node_modules/@eslint/eslintrc/lib/config-array-factory.js:290:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (/var/www/app/node_modules/@eslint/eslintrc/lib/config-array-factory.js:883:23)
    at ConfigArrayFactory._loadExtends (/var/www/app/node_modules/@eslint/eslintrc/lib/config-array-factory.js:781:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/var/www/app/node_modules/@eslint/eslintrc/lib/config-array-factory.js:720:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/var/www/app/node_modules/@eslint/eslintrc/lib/config-array-factory.js:665:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.loadInDirectory (/var/www/app/node_modules/@eslint/eslintrc/lib/config-array-factory.js:511:28)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/var/www/app/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:379:46)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/var/www/app/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:398:20)
```

I use webpack eslint-loader and ESLint.

### What's the expected result?

- Avoid this error

### etc
I think this warning occurred because .config/eslint.config is nothing.
Why package.json includes .config/eslint.config this?
`
"eslintConfig": {
    "extends": "./.config/eslint.config"
  },
`
And I think this issue(https://github.com/floating-ui/floating-ui/issues/1105) is related.
Why closed this?

**Comment by atomiks** [comment]
The problem is environmental and doesn't have to do with `@popperjs/core`. Your build tool should be ignoring `node_modules` entirely. 

The eslint config is specified in `package.json` because it reduces pollution of the root directory, making it faster to reach the README.

**Comment by yodakaEngineer** [comment]
@atomiks Oh, finally I make sense.

I added this to eslint-loader section in webpack.config.js.
```
exclude: /node_modules/,
```
And it works.

Sorry for the question of my lack of knowledge.
And Thank you for your quick response.

**Comment by brense** [comment]
`"exclude": "node_modules"` does not work for me.
I'm using `vite build` to build a project that includes `@mui/material` which includes `@popperjs/core`

```
vite v3.0.7 building for production...
✓ 818 modules transformed.
[commonjs--resolver] Failed to load config "./.config/eslint.config" to extend from.
Referenced from: [...]\node_modules\@popperjs\core\package.json
file: [...]/node_modules/@popperjs/core/lib/index.js
```

**Comment by brense** [comment]
`"exclude": "node_modules"` does not work for me.
I'm using `vite build` to build a project that includes `@mui/material` which includes `@popperjs/core`

```
vite v3.0.7 building for production...
✓ 818 modules transformed.
[commonjs--resolver] Failed to load config "./.config/eslint.config" to extend from.
Referenced from: [...]\node_modules\@popperjs\core\package.json
file: [...]/node_modules/@popperjs/core/lib/index.js
```

**Comment by brense** [comment]
Ok, looks like the "culprit" was the `vite-plugin-eslint` although it didnt complain about any other packages except @popperjs...
I changed my config for the plugin to explicitly exclude node_modules (which is the default according to their documentation, but it doesnt seem to work properly).

```ts
export default defineConfig({
  ...otherConfig,
  plugins: [...otherPlugins, eslint({
    exclude: ['**/node_modules/**']
  })]
})
```
