### ISSUE TITLE
Issue when setting up with Svelte

### ISSUE THREAD

**Issue by anotherempty** [floating-ui/floating-ui#1713]
Hi, I'm trying to use floating-ui with Svelte and Rollup but keep getting this error : 

```
Uncaught (in promise) ReferenceError: process is not defined
    at computePosition$1 (floating-ui.core.mjs:97:3)
```
I followed the tutorial by installing with `npm install @floating-ui/dom`. Same error happens using the CDN with Svelte.

If I remove everything that checks whether `process.env.NODE_ENV !== "production"` from the source file, everything seems to work fine. 
What bug can I expect after removing this ? Or is there a better way to setting things up ?

**Comment by atomiks** [comment]
Did you read https://github.com/floating-ui/floating-ui#package-entry-points?

**Comment by gspasov** [comment]
This doesn't seem to work. Even with `exportConditions: ["development"],` added to rollup.config.js I still get
```
Uncaught (in promise) ReferenceError: process is not defined
    at computePosition$1 (floating-ui.core.mjs:97:3)
```
For some reason there are no issues when using in `svelte-kit`, but in a simple `svelte` project this issue persists even after the change.

**Comment by atomiks** [comment]
The `browser: true` option should be selecting the `floating-ui.core.browser.js` file, but in your case it is not for whatever reason. As a fallback you can use `replace` plugin to replace `process.env.NODE_ENV` as a string to `true/false`

**Comment by gspasov** [comment]
This is what I added in plugins in `rollup.config.js` in order to make it work:
```js
  replace({
    "process.env.NODE_ENV": production ? "production" : "development",
  }),
```
_(the 'production' variable is just `process.env.ROLLUP_WATCH`. The library for the replace plugin is `@rollup/plugin-replace`)_
