### ISSUE TITLE
function _isWithActiveTrigger causes an error

### ISSUE THREAD

**Issue by njmkramer** [floating-ui/floating-ui#1948]
Uncaught TypeError: Cannot convert undefined or null to object
			    at Function.values (<anonymous>)
			    at Popover._isWithActiveTrigger (tooltip.js:549:19)
			    at complete (tooltip.js:279:16)
			    at execute (index.js:254:5)
			    at HTMLDivElement.handler (index.js:276:5)
			    at triggerTransitionEnd (index.js:98:11)
			    at index.js:282:7

This happens when multiple elements have a popover or a popover is attached to a new element and fast switching hover on elements.

suggestion:
 _isWithActiveTrigger() {
   if(typeof this._activeTrigger == 'undefined' || this._activeTrigger === null){
     return false;
   }
   return Object.values(this._activeTrigger).includes(true)
 }

**Comment by atomiks** [comment]
This code doesn't exist within this library. Looks like Bootstrap from a quick code search, should file the issue there instead.
