### ISSUE TITLE
[Preact] Cannot read properties of undefined (reading 'transition')

### ISSUE THREAD

**Issue by ynwd** [floating-ui/floating-ui#2543]
### Discussed in https://github.com/floating-ui/floating-ui/discussions/2542

<div type='discussions-op-text'>

<sup>Originally posted by **ynwd** September 11, 2023</sup>
I use preact and deno, btw.

But always got this error:

```
index.js:9 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'transition')
    at Nn (index.js:9:37013)
    at a.flushSync (index.js:9:56210)
    at index.js:9:59739
```

Is something missing?
</div>

**Comment by ynwd** [comment]
Solved
https://github.com/denoland/fresh/issues/1395
