### ISSUE TITLE
TypeError: Cannot convert undefined or null to object after updating @floating-ui/utils to 0.2.6

### ISSUE THREAD

**Issue by ankit-virani** [floating-ui/floating-ui#2997]
After updating **@floating-ui/utils** to version **0.2.6**, I encountered the following error:

```
Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.getPrototypeOf (<anonymous>)
    at lM (index.js:1771:20654)
    at Ph (index.js:1771:21718)
    at Tze (index.js:1771:24606)
    at Object.Cze [as getElementRects] (index.js:1771:25265)
    at async tze (index.js:1771:10145)
```
This error occurs in a VSCode extension where the React app loads in an iframe.

**Potential Cause**

The issue might be triggered from the following code in **packages/utils/src/dom.ts**:
```
export function getFrameElement(win: Window): Element | null {
  return Object.getPrototypeOf(win.parent) ? win.frameElement : null;
}
```

**Additional context**

- @blocknote/core version: 0.14.5
- @floating-ui/utils version: 0.2.6
- VSCode version: 1.91.1
- OS: macOS

Thank you

**Comment by ankit-virani** [comment]
@atomiks Thank you ☺️
